apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd
  namespace: argocd
  labels:
   app.kubernetes.io/instance: jumia-devops
  annotations:
   kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: argocd.tizok8s.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: argocd-server
            port:
              number: 8080
